name: 'Migrate Down'
description: 'Reverts deployed migration files on a target database'
branding:
  icon: database
author: 'Ariga'
inputs:
  url:
    description: "The URL of the target database. For example: `mysql://root:pass@localhost:3306/dev`."
    required: false
  dir:
    description: |
      The URL of the migration directory to apply. For example: `atlas://dir-name` for cloud
      based directories or `file://migrations` for local ones.
    required: false
  config:
    description: |
      The URL of the Atlas configuration file. By default, Atlas will look for a file
      named `atlas.hcl` in the current directory. For example, `file://config/atlas.hcl`.
      Learn more about [Atlas configuration files](https://atlasgo.io/atlas-schema/projects).
    required: false
  dev-url:
    description: |
      The URL of the dev-database to use for analysis. For example: `mysql://root:pass@localhost:3306/dev`.
      Read more about [dev-databases](https://atlasgo.io/concepts/dev-database).
    required: true
  env:
    description: The environment to use from the Atlas configuration file.  For example, `dev`.
    required: false
  amount:
    description: The amount of applied migrations to revert. Mutually exclusive with `to-tag` and `to-version`.
    required: false
  to-version:
    description: The version to revert to. Mutually exclusive with `amount` and `to-tag`.
    required: false
  to-tag:
    description: The tag to revert to. Mutually exclusive with `amount` and `to-version`.
    required: false
  working-directory:
    description: Atlas working directory, default is project root
    required: false
  wait-interval:
    description: Time in seconds between different migrate down attempts.
    required: false
  wait-timeout:
    description: Time after which no other retry attempt is made and the action exits.
    required: false
  vars:
    description: |
      A JSON object containing variables to be used in the Atlas configuration file.
      For example, `{"var1": "value1", "var2": "value2"}`.
    required: false
outputs:
  current:
    description: The current version of the database. (before applying migrations)
  target:
    description: The target version of the database.
  planned_count:
    description: The number of migrations that will be applied.
  reverted_count:
    description: The number of migrations that were reverted.
  url:
    description: If given, the URL for reviewing the revert plan.
runs:
  using: node20
  main: dist/index.js
