name: 'atlas-ci-action'
description: 'CI for database schema changes with Atlas'
branding:
  icon: database
author: 'Ariga'
inputs:
  atlas-version:
    description: 'Which version of Atlas CLI to install'
    required: false
    default: 'latest'
  dir:
    description: 'select migration directory relative to working directory'
    required: false
  dir-name:
    description: 'target migration directory name (slug)'
    required: false
  dir-format:
    description: 'Dir format for migration files ("atlas", "golang-migrate", "goose", "flyway", "liquibase", "dbmate")'
    required: false
  dev-url:
    description: 'select development db URL using atlas URL format'
    required: false
  latest:
    description: 'run analysis on the latest N migration files'
    required: false
  working-directory:
    description: 'path to the repository working directory'
    required: false
  ariga-token:
    description: 'Token for sending report to Atlas Cloud (should be passed as a secret). Deprecated.'
    required: false
  cloud-token:
    description: 'Token for using Atlas Cloud (should be passed as a secret).'
    required: false
  cloud-public:
    description: 'Set true to send report to gh.atlasgo.cloud'
    default: false
    required: false
  schema-insights:
    description: 'Enable reporting of schema insights (requires cloud-token)'
    default: 'true'
    required: false
  project-env:
    description: "The env from the atlas.hcl project file to use (Deprecated use config-env instead)"
    required: false
  token:
    description: "GitHub token passed to the action"
    default: ${{ github.token }}
  skip-check-for-update:
    description: 'Set true to skip check for update'
    default: false
  config-path:
    description: 'Path to the atlas.hcl file'
    required: false
  config-env:
    description: 'The name of the env to select in the atlas.hcl file'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
