name: 'Atlas'
description: 'Lint schema migration directories with Atlas'
author: 'Ariga'
inputs:
  atlas-version:
    description: 'Which version of Atlas CLI to install'
    required: false
    default: 'v0.7.0'
  dir:
    description: 'select migration directory relative to working directory'
    required: false
  dir-format:
    description: 'Dir format for migration files ("atlas", "golang-migrate", "goose", "flyway", "liquibase", "dbmate")'
    required: false
  dev-url:
    description: 'select development db URL using atlas URL format'
    required: false
  latest:
    description: 'run analysis on the latest N migration files'
    required: false
  working-directory:
    description: 'path to the repository working directory'
    required: false
  ariga-token:
    description: 'Token for sending report to Ariga cloud (should be passed as a secret)'
    required: false
  schema-insights:
    description: 'Enable reporting of schema insights (requires ariga-token)'
    default: 'true'
    required: false
  project-env:
    description: "The env from the atlas.hcl project file to use"
    required: false
  token:
    description: "GitHub token passed to the action"
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'