name: 'Atlas Schema Monitoring'
description: 'Sync the database schema to Atlas Cloud.'
branding:
  icon: database
author: 'Ariga'
inputs:
  cloud-token:
    description: 'The token that is used to connect to Atlas Cloud (should be passed as a secret).'
    required: true
  url:
    description: 'URL of the database to sync (mutually exclusive with `config` and `env`).'
    required: false
  config:
    description: 'The URL of the Atlas configuration file (mutually exclusive with `url`).
      For example, `file://config/atlas.hcl`, learn more about [Atlas configuration files](https://atlasgo.io/atlas-schema/projects).'
    required: false
  env:
    description: 'The environment to use from the Atlas configuration file. For example, `dev` (mutually exclusive with `url`).'
    required: false
  slug:
    description: 'Optional unique identifier for the database server.'
    required: false
  schemas:
    description: 'List of database schemas to include (by default includes all schemas).
     see: https://atlasgo.io/declarative/inspect#inspect-multiple-schemas'
    required: false
  exclude:
    description: 'List of exclude patterns from inspection.   
     see: https://atlasgo.io/declarative/inspect#exclude-schemas'
    required: false
outputs:
  url:
    description: 'URL of the schema of the database inside Atlas Cloud.'
runs:
  using: node20
  main: index.js
