name: 'Migrate Auto Rebase'
description: Resolve conflicts in the migration directory by rebasing the current branch's migrations on top of the rebase branch migration directory.
branding:
  icon: database
author: 'Ariga'
inputs:
  rebase-branch:
    description: The branch to rebase on, default is `main`.
    required: false
  working-directory:
    description: Atlas working directory, default is project root
    required: false
  dir:
    description: |
      The URL of the migration directory to rebase on. By default: `file://migrations`.
    required: false
runs:
  using: node20
  main: index.js
