name: 'Migrate Auto Rebase'
description: 'Fix conflicts in migration directory by rebasing migrations of the current branch on top of the migration directory'
branding:
  icon: database
author: 'Ariga'
inputs:
  working-directory:
    description: Atlas working directory, default is project root
    required: false
  dir:
    description: |
      The URL of the migration directory to rebase on. By default: `file://migrations`.
    required: false
runs:
  using: node20
  main: index.js
