name: 'Migrate Auto Rebase'
description: 'Fix conflicts in migration directory by rebasing migrations of the current branch on top of the migration directory'
branding:
  icon: database
author: 'Ariga'
inputs:
  working-directory:
    description: Atlas working directory, default is project root
    required: false
  dir:
    description: |
      The URL of the migration directory to rebase on. By default: `file://migrations`.
    required: false
  config:
    description: |
      The URL of the Atlas configuration file. By default, Atlas will look for a file
      named `atlas.hcl` in the current directory. For example, `file://config/atlas.hcl`.
      Learn more about [Atlas configuration files](https://atlasgo.io/atlas-schema/projects).
    required: false
  env:
    description: The environment to use from the Atlas configuration file.  For example, `dev`.
    required: false
  vars:
    description: |
      A JSON object containing variables to be used in the Atlas configuration file.
      For example, `{"var1": "value1", "var2": "value2"}`.
    required: false
runs:
  using: node20
  main: index.js
