name: 'Migrate Apply'
description: 'Applies a migration directory on a target database'
branding:
  icon: database
author: 'Ariga'
inputs:
  url:
    description: "The URL of the target database.  For example: `mysql://root:pass@localhost:3306/dev`."
    required: false
  dir:
    description: |
      The URL of the migration directory to apply.  For example: `atlas://dir-name` for cloud
      based directories or `file://migrations` for local ones.
    required: false
  config:
    description: |
      The URL of the Atlas configuration file.  By default, Atlas will look for a file
      named `atlas.hcl` in the current directory. For example, `file://config/atlas.hcl`.
      Learn more about [Atlas configuration files](https://atlasgo.io/atlas-schema/projects).
    required: false
  env:
    description: The environment to use from the Atlas configuration file.  For example, `dev`.
    required: false
  dry-run:
    description: Print SQL without executing it. Either "true" or "false".
    required: false
  working-directory:
    description: Atlas working directory, default is project root
    required: false
outputs:
  current:
    description: The current version of the database. (before applying migrations)
  target:
    description: The target version of the database.
  pending_count:
    description: The number of migrations that will be applied.
  applied_count:
    description: The number of migrations that were applied.
runs:
  using: node20
  main: dist/index.js
