name: 'Migrate Apply'
description: 'Applies a migration directory on a target database'
branding:
  icon: database
author: 'Ariga'
inputs:
  url:
    description: The database URL (i.e mysql://root:pass@localhost:3306/dev)
    required: false
  dir:
    description: The migration directory URL (i.e file://path/to/migrations)
    required: false
  config:
    description: The url of the configuration
    required: false
  env:
    description: The environment to use with the configuration file.
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.21"
    - name: Run
      shell: bash
      run: go run -mod=mod ./cmd/atlas-action --action migrate/apply