name: "Migrate Push"
description: "Push the current version of your migration directory to Atlas Cloud."
branding:
  icon: database
author: "Ariga"
inputs:
  dir:
    description: |
      The URL of the migration directory to push.  For example: `file://migrations`.
      Read more about [Atlas URLs](https://atlasgo.io/concepts/url).
    required: false
  dir-name:
    description: The name (slug) of the project in Atlas Cloud.
    required: false
  dev-url:
    description: |
      The URL of the dev-database to use for analysis.  For example: `mysql://root:pass@localhost:3306/dev`.
      Read more about [dev-databases](https://atlasgo.io/concepts/dev-database).
    required: false
  tag:
    description: |
      The tag to apply to the pushed migration directory.  By default the
      current git commit hash is used.
    required: false
  config:
    description: |
      The path to the Atlas configuration file. By default, Atlas will look for a file
      named `atlas.hcl` in the current directory. For example, `file://config/atlas.hcl`.
      Learn more about [Atlas configuration files](https://atlasgo.io/atlas-schema/projects).
    required: false
  env:
    description: The environment to use from the Atlas configuration file.  For example, `dev`.
    required: false
  working-directory:
    description: Atlas working directory, default is project root
    required: false
  vars:
    description: |
      A JSON object containing variables to be used in the Atlas configuration file.
      For example, `{"var1": "value1", "var2": "value2"}`.
    required: false
runs:
  using: node20
  main: dist/index.js
