name: 'Schema Lint'
description: 'Lint database schema with Atlas'
branding:
  icon: database
author: 'Ariga'
inputs:
  working-directory:
    description: Atlas working directory, default is project root
    required: false
  config:
    description: |
      The path to the Atlas configuration file. By default, Atlas will look for a file
      named `atlas.hcl` in the current directory. For example, `file://config/atlas.hcl`.
      Learn more about [Atlas configuration files](https://atlasgo.io/atlas-schema/projects).
    required: false
  env:
    description: The environment to use from the Atlas configuration file. For example, `dev`.
    required: false
  vars:
    description: |
      A JSON object containing variables to be used in the Atlas configuration file.
      For example, `{"var1": "value1", "var2": "value2"}`.
    required: false
  dev-url:
    description: |
      The URL of the dev-database to use for analysis. For example: `mysql://root:pass@localhost:3306/dev`.
      Read more about [dev-databases](https://atlasgo.io/concepts/dev-database).
    required: true
  url:
    description: |
      Schema URL(s) to lint. For example: `file://schema.hcl`.
      Read more about [Atlas URLs](https://atlasgo.io/concepts/url).
    required: true
  schema:
    description: The database schema(s) to include. For example: `public`.
    required: false
runs:
  using: node20
  main: index.js 