// Copyright 2021-present The Atlas Authors. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

package atlasaction

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"ariga.io/atlas/atlasexec"
	"ariga.io/atlas/sql/migrate"
	"github.com/stretchr/testify/require"
)

func TestSchemaPlanComment(t *testing.T) {
	var body string // The last comment posted.
	h := http.NewServeMux()
	h.HandleFunc("GET /repos/ariga/atlas-action/issues/1/comments", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})
	h.HandleFunc("POST /repos/ariga/atlas-action/issues/1/comments", func(w http.ResponseWriter, r *http.Request) {
		var c struct {
			Body string `json:"body"`
		}
		require.NoError(t, json.NewDecoder(r.Body).Decode(&c))
		body = c.Body
		w.WriteHeader(http.StatusCreated)
		fmt.Fprint(w, `{}`)
	})
	srv := httptest.NewServer(h)
	t.Cleanup(srv.Close)
	gh, err := NewGitHubClient("ariga/atlas-action", srv.URL, "token")
	require.NoError(t, err)
	var (
		ctx  = context.Background()
		tc   = &TriggerContext{PullRequest: &PullRequest{Number: 1}}
		plan = &atlasexec.SchemaPlan{
			Repo: "app",
			File: &atlasexec.SchemaPlanFile{
				Name:      "pr-1-Rl4lBdMk",
				Migration: "-- Create \"users\" table\nCREATE TABLE `users` (\n  `id` integer NOT NULL\n);\n",
				Stmts:     []*migrate.Stmt{{Pos: 24, Text: "CREATE TABLE `users` (\n  `id` integer NOT NULL\n);"}},
				Changes: &atlasexec.ChangeSummary{
					Objects: []*atlasexec.ObjectChange{
						{Type: "table", Op: "add", Object: `table "users"`, Diff: "+CREATE TABLE `users` (\n+  `id` integer NOT NULL\n+);", Stmts: []int{0}},
					},
					Stmts: 1,
				},
				Link: "https://gh.atlasgo.cloud/plan/pr-1-Rl4lBdMk",
			},
			Lint: &atlasexec.SummaryReport{},
		}
	)
	require.NoError(t, gh.CommentPlan(ctx, tc, plan))
	for _, s := range []string{
		"<details open><summary><strong>Change summary</strong> · 1 object: 1 added · 1 statement</summary><p></p>\n<table>",
		"<tr><th>Object</th><th>Diff</th><th>Statements</th></tr>",
		"<td><code>+</code> <code>table \"users\"</code></td>",
		// Comments color the counts of a collapsed diff.
		"<td><details><summary><kbd>$\\color{#2ea043}{\\texttt{+3}}$</kbd></summary>\n\n```diff\n+CREATE TABLE `users` (\n+  `id` integer NOT NULL\n+);\n```\n\n</details></td>",
		"<td><details><summary>1 statement</summary>\n\n```sql\nCREATE TABLE `users` (\n  `id` integer NOT NULL\n);\n```\n\n</details></td>",
		"</table>\n</details>\n<details><summary><strong>Migration script</strong> · 1 statement, 4 lines</summary><p></p>",
	} {
		require.Contains(t, body, s)
	}
	require.True(t, strings.HasSuffix(body, "\n<!-- generated by ariga/atlas-action for pr-1-Rl4lBdMk -->"))

	// Large plans fit the limit of GitHub, with their whole migration: the
	// summary is collapsed and shows statement counts only, and then is left out.
	for n, summary := range map[int]string{120: "<details><summary><strong>Change summary</strong> · 120 objects: 120 added · 120 statements</summary>", 300: ""} {
		p := &atlasexec.SchemaPlan{Repo: "app", File: changesPlan(n).File, Lint: &atlasexec.SummaryReport{}}
		require.NoError(t, gh.CommentPlan(ctx, tc, p))
		require.Contains(t, body, strings.Trim(p.File.Migration, "\n"))
		require.LessOrEqual(t, len(body), 65536)
		if summary != "" {
			require.Contains(t, body, summary)
			require.Contains(t, body, "<td>1 statement</td>")
		} else {
			require.NotContains(t, body, "<th>Object</th>")
		}
	}
}

func TestRenderPlanComment_Limit(t *testing.T) {
	var (
		p    = changesPlan(20)
		size = func(sql bool) int {
			s, err := RenderTemplate("schema-plan.tmpl", &PlanComment{Plan: p, Summary: true, SummarySQL: sql}, nil)
			require.NoError(t, err)
			return len(s)
		}
		full, counts, before = size(true), size(false), render(t, withoutChanges(p))
	)
	require.Greater(t, full, counts)
	require.Greater(t, counts, len(before))
	// With the statements of each object, if they fit.
	c := &PlanComment{Plan: p}
	s, err := renderPlanComment(nil, c, full)
	require.NoError(t, err)
	require.True(t, c.Summary)
	require.True(t, c.SummarySQL)
	require.Len(t, s, full)
	require.Contains(t, s, "<td><details><summary>1 statement</summary>")
	// With their counts only, if they don't.
	s, err = renderPlanComment(nil, c, full-1)
	require.NoError(t, err)
	require.True(t, c.Summary)
	require.False(t, c.SummarySQL)
	require.Len(t, s, counts)
	require.Contains(t, s, "<td>1 statement</td>")
	// As before the summary, if even that doesn't fit.
	s, err = renderPlanComment(nil, c, counts-1)
	require.NoError(t, err)
	require.False(t, c.Summary)
	require.Equal(t, before, s)
	// The migration is kept in all of them.
	for _, sql := range []bool{true, false} {
		s, err := RenderTemplate("schema-plan.tmpl", &PlanComment{Plan: p, Summary: true, SummarySQL: sql}, nil)
		require.NoError(t, err)
		require.Contains(t, s, "<details><summary><strong>Migration script</strong> · 20 statements, 120 lines</summary>")
		require.Contains(t, s, "```sql\n"+strings.Trim(p.File.Migration, "\n")+"\n```")
	}
}

func TestRenderPlanComment_NoSummary(t *testing.T) {
	for reason, change := range map[string]func(*atlasexec.SchemaPlanFile){
		"no summary": func(f *atlasexec.SchemaPlanFile) {
			f.Changes = nil
		},
		"empty summary": func(f *atlasexec.SchemaPlanFile) {
			f.Changes = &atlasexec.ChangeSummary{Stmts: len(f.Stmts)}
		},
		"nil object": func(f *atlasexec.SchemaPlanFile) {
			f.Changes.Objects[1] = nil
		},
	} {
		t.Run(reason, func(t *testing.T) {
			p := changesPlan(3)
			change(p.File)
			c := &PlanComment{Plan: p}
			s, err := renderPlanComment(nil, c, githubCommentLimit)
			require.NoError(t, err)
			require.False(t, c.Summary)
			require.Equal(t, render(t, withoutChanges(p)), s)
		})
	}
	// Other SCMs pass a map, and get the comment as before the summary.
	p := changesPlan(3)
	s, err := RenderTemplate("schema-plan.tmpl", map[string]any{"Plan": p}, nil)
	require.NoError(t, err)
	require.Equal(t, render(t, withoutChanges(p)), s)
}

func TestRenderPlanComment_Changes(t *testing.T) {
	var (
		p      = mixedPlan()
		c      = &PlanComment{Plan: p, Colors: true}
		s, err = renderPlanComment(nil, c, githubCommentLimit)
	)
	require.NoError(t, err)
	require.True(t, c.SummarySQL)
	for _, want := range []string{
		"<details open><summary><strong>Change summary</strong> · 6 objects: 1 added, 2 modified, 1 renamed, 2 dropped · 9 statements, 2 of them recreate dependent objects</summary>",
		// Added and dropped objects, and long diffs, open from their line counts.
		"<td><code>+</code> <code>table \"users\"</code></td>\n<td><details><summary><kbd>$\\color{#2ea043}{\\texttt{+3}}$</kbd></summary>\n\n```diff\n+CREATE TABLE",
		"<td><code>-</code> <code>view \"old\"</code></td>\n<td><details><summary><kbd>$\\color{#da3633}{\\texttt{-2}}$</kbd></summary>",
		"<td><details><summary><kbd>$\\color{#2ea043}{\\texttt{+1,200}}$</kbd> <kbd>$\\color{#da3633}{\\texttt{-1,100}}$</kbd></summary>",
		// Short diffs of modified objects are shown in their rows.
		"<td><code>~</code> <code>table \"orders\"</code></td>\n<td>\n\n```diff\n   \"id\" int NOT NULL,\n-  \"total\" int NULL\n+  \"total\" bigint NULL\n```\n\n</td>",
		"<td><code>~</code> <code>table \"clients\"</code></td>\n<td>\n\n```diff\n-CREATE TABLE \"customers\" (\n+CREATE TABLE \"clients\" (\n```\n\n</td>",
		// Statements open from their counts.
		"<td><details><summary>3 statements, 2 recreate dependents</summary>\n\n```sql\nDROP VIEW \"totals\";\nALTER TABLE \"orders\" ALTER COLUMN \"total\" TYPE bigint;\nCREATE VIEW \"totals\" AS SELECT sum(total) FROM orders;\n```\n\n</details></td>",
		"<tr>\n<td>other statements</td>\n<td></td>\n<td><details><summary>1 statement</summary>\n\n```sql\nSET lock_timeout = '5s';\n```\n\n</details></td>\n</tr>",
	} {
		require.Contains(t, s, want)
	}
	// Job summaries may not render math, so their counts are plain.
	s, err = renderPlanComment(nil, &PlanComment{Plan: p}, githubCommentLimit)
	require.NoError(t, err)
	require.Contains(t, s, "<summary><kbd>+1,200</kbd> <kbd>-1,100</kbd></summary>")
	require.NotContains(t, s, "\\color")
}

func TestRenderPlanComment_Labels(t *testing.T) {
	p := changesPlan(1)
	p.File.Changes.Objects[0].Object = `operator "@<->#1"`
	s, err := renderPlanComment(nil, &PlanComment{Plan: p}, githubCommentLimit)
	require.NoError(t, err)
	require.Contains(t, s, `<td><code>+</code> <code>operator "@&lt;-&gt;#1"</code></td>`)
	require.Contains(t, s, "<summary><strong>Change summary</strong> · 1 object: 1 added · 1 statement</summary>")
}

func TestRenderPlanComment_Collapsed(t *testing.T) {
	// The change summary is open, unless it has more than 15 objects.
	for n, want := range map[int]string{
		15: "<details open><summary><strong>Change summary</strong> · 15 objects: 15 added · 15 statements</summary>",
		16: "<details><summary><strong>Change summary</strong> · 16 objects: 16 added · 16 statements</summary>",
	} {
		s, err := renderPlanComment(nil, &PlanComment{Plan: changesPlan(n)}, githubCommentLimit)
		require.NoError(t, err)
		require.Contains(t, s, want)
	}
}

func TestRenderPlanComment_OtherOnly(t *testing.T) {
	// A summary of statements that change no object has no object counts.
	p := changesPlan(2)
	p.File.Changes = &atlasexec.ChangeSummary{Other: []int{0, 1}, Stmts: 2}
	s, err := renderPlanComment(nil, &PlanComment{Plan: p}, githubCommentLimit)
	require.NoError(t, err)
	require.Contains(t, s, "<details open><summary><strong>Change summary</strong> · 2 statements</summary>")
	require.Contains(t, s, "<tr>\n<td>other statements</td>\n<td></td>\n<td><details><summary>2 statements</summary>")
}

func TestRenderPlanComment_Delimiter(t *testing.T) {
	p := changesPlan(2)
	p.File.Migration = "-- atlas:delimiter \\nGO\n\n" + strings.ReplaceAll(p.File.Migration, ");\n", ");\nGO\n")
	s, err := renderPlanComment(nil, &PlanComment{Plan: p}, githubCommentLimit)
	require.NoError(t, err)
	require.Contains(t, s, "```sql\n"+p.File.Stmts[1].Text+"\nGO\n```")
}

func TestFence(t *testing.T) {
	// Same as a code block for code without a fence line.
	require.Equal(t, "```sql\nSELECT '```' AS a;\n```", fence("sql", "\nSELECT '```' AS a;\n"))
	require.Equal(t, "````diff\n-a\n ```\n+b\n````", fence("diff", "-a\n ```\n+b"))
	require.Equal(t, "``````\n`````\n``````", fence("", "`````"))
}

func TestThousands(t *testing.T) {
	for n, want := range map[int]string{0: "0", 7: "7", 999: "999", 1000: "1,000", 65536: "65,536", 1234567: "1,234,567", -1200: "-1,200"} {
		require.Equal(t, want, thousands(n))
	}
	require.Equal(t, "1 line", plural(1, "line"))
	require.Equal(t, "0 lines", plural(0, "line"))
	require.Equal(t, "1,005 lines", plural(1005, "line"))
}

// changesPlan returns a plan that creates n tables, with a change summary.
func changesPlan(n int) *atlasexec.SchemaPlan {
	f := &atlasexec.SchemaPlanFile{
		Name:    "20260930120000",
		URL:     "atlas://app/plans/20260930120000",
		Link:    "https://test.atlasgo.cloud/schemas/1/plans/2",
		Status:  "PENDING",
		Changes: &atlasexec.ChangeSummary{Stmts: n},
	}
	var migration strings.Builder
	for i := range n {
		stmt := fmt.Sprintf("CREATE TABLE \"t%d\" (\n  \"id\" integer NOT NULL,\n  \"name\" text NOT NULL,\n  PRIMARY KEY (\"id\")\n);", i)
		fmt.Fprintf(&migration, "-- Create \"t%d\" table\n", i)
		f.Stmts = append(f.Stmts, &migrate.Stmt{Pos: migration.Len(), Text: stmt})
		fmt.Fprintln(&migration, stmt)
		f.Changes.Objects = append(f.Changes.Objects, &atlasexec.ObjectChange{
			Type:   "table",
			Op:     "add",
			Object: fmt.Sprintf("table \"t%d\"", i),
			Diff:   "+" + strings.ReplaceAll(stmt, "\n", "\n+"),
			Stmts:  []int{i},
		})
	}
	f.Migration = migration.String()
	return &atlasexec.SchemaPlan{Repo: "app", File: f, Lint: &atlasexec.SummaryReport{}}
}

// mixedPlan returns a plan with an object of each change, and a statement that changes none.
func mixedPlan() *atlasexec.SchemaPlan {
	stmts := []string{
		"CREATE TABLE \"users\" (\n  \"id\" int NOT NULL\n);",
		"DROP VIEW \"totals\";",
		"ALTER TABLE \"orders\" ALTER COLUMN \"total\" TYPE bigint;",
		"CREATE VIEW \"totals\" AS SELECT sum(total) FROM orders;",
		"CREATE OR REPLACE FUNCTION \"report\"() RETURNS void AS $$ BEGIN END $$ LANGUAGE plpgsql;",
		"ALTER TABLE \"customers\" RENAME TO \"clients\";",
		"DROP VIEW \"old\";",
		"DROP VIEW \"older\";",
		"SET lock_timeout = '5s';",
	}
	var long strings.Builder
	for i := range 1200 {
		if i < 1100 {
			fmt.Fprintf(&long, "-  SELECT %d;\n", i)
		}
		fmt.Fprintf(&long, "+  PERFORM %d;\n", i)
	}
	f := &atlasexec.SchemaPlanFile{
		Name:      "20260930120000",
		Link:      "https://test.atlasgo.cloud/schemas/1/plans/2",
		Migration: strings.Join(stmts, "\n") + "\n",
		Changes: &atlasexec.ChangeSummary{
			Objects: []*atlasexec.ObjectChange{
				{Type: "table", Op: "add", Object: `table "users"`, Diff: "+CREATE TABLE \"users\" (\n+  \"id\" int NOT NULL\n+);", Stmts: []int{0}},
				{Type: "table", Op: "modify", Object: `table "orders"`, Diff: "   \"id\" int NOT NULL,\n-  \"total\" int NULL\n+  \"total\" bigint NULL", Stmts: []int{1, 2, 3}, Dependents: 2},
				{Type: "function", Op: "modify", Object: `function "report"`, Diff: long.String(), Stmts: []int{4}},
				{Type: "table", Op: "rename", Object: `table "clients"`, Diff: "-CREATE TABLE \"customers\" (\n+CREATE TABLE \"clients\" (", Stmts: []int{5}},
				{Type: "view", Op: "drop", Object: `view "old"`, Diff: "-CREATE VIEW \"old\" AS\n-SELECT 1;", Stmts: []int{6}},
				{Type: "view", Op: "drop", Object: `view "older"`, Diff: "-CREATE VIEW \"older\" AS\n-SELECT 2;", Stmts: []int{7}},
			},
			Other:      []int{8},
			Stmts:      len(stmts),
			Dependents: 2,
		},
	}
	for _, s := range stmts {
		f.Stmts = append(f.Stmts, &migrate.Stmt{Text: s})
	}
	return &atlasexec.SchemaPlan{Repo: "app", File: f, Lint: &atlasexec.SummaryReport{}}
}

// withoutChanges returns a copy of the plan without a change summary.
func withoutChanges(p *atlasexec.SchemaPlan) *atlasexec.SchemaPlan {
	f := *p.File
	f.Changes = nil
	return &atlasexec.SchemaPlan{Repo: p.Repo, File: &f, Lint: p.Lint}
}

// render renders the plan comment as before the change summary.
func render(t *testing.T, p *atlasexec.SchemaPlan) string {
	t.Helper()
	s, err := RenderTemplate("schema-plan.tmpl", &PlanComment{Plan: p}, nil)
	require.NoError(t, err)
	return s
}

func TestLintComment(t *testing.T) {
	var body string // The last comment posted.
	h := http.NewServeMux()
	h.HandleFunc("GET /repos/ariga/atlas-action/issues/1/comments", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})
	h.HandleFunc("POST /repos/ariga/atlas-action/issues/1/comments", func(w http.ResponseWriter, r *http.Request) {
		var c struct {
			Body string `json:"body"`
		}
		require.NoError(t, json.NewDecoder(r.Body).Decode(&c))
		body = c.Body
		w.WriteHeader(http.StatusCreated)
		fmt.Fprint(w, `{}`)
	})
	h.HandleFunc("GET /repos/ariga/atlas-action/pulls/1/files", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})
	srv := httptest.NewServer(h)
	t.Cleanup(srv.Close)
	gh, err := NewGitHubClient("ariga/atlas-action", srv.URL, "token")
	require.NoError(t, err)
	var (
		ctx = context.Background()
		act = NewGitHub(func(k string) string {
			if k == "INPUT_DIR-NAME" {
				return "app"
			}
			return ""
		}, io.Discard)
		tc = &TriggerContext{PullRequest: &PullRequest{Number: 1}, Act: act}
	)
	require.NoError(t, gh.CommentLint(ctx, tc, lintReport(lintFile("1_users.sql", 1), dataFile("2_seed.sql"))))
	for _, s := range []string{
		"<details open><summary><strong>Changes in</strong> <code>1_users.sql</code> · 1 object: 1 added · 1 statement</summary><p></p>\n<table>",
		// Comments color the counts of a collapsed diff.
		"<td><details><summary><kbd>$\\color{#2ea043}{\\texttt{+3}}$</kbd></summary>",
		"<td><details><summary>1 statement</summary>\n\n```sql\nCREATE TABLE \"1_users_t0\" (\n  \"id\" integer NOT NULL\n);\n```\n\n</details></td>",
	} {
		require.Contains(t, body, s)
	}
	// The data file is in the lint table, but has no section.
	require.Contains(t, body, "2_seed.sql")
	require.NotContains(t, body, "<code>2_seed.sql</code>")
	require.True(t, strings.HasSuffix(body, "</table>\n</details>\n<!-- generated by ariga/atlas-action for app -->"))

	// Large reports fit the limit of GitHub: the summary shows statement counts only, and then is left out.
	for n, summary := range map[int]string{250: "<details><summary><strong>Changes in</strong> <code>1_big.sql</code> · 250 objects: 250 added · 250 statements</summary>", 300: ""} {
		r := lintReport(lintFile("1_big.sql", n))
		require.NoError(t, gh.CommentLint(ctx, tc, r))
		require.LessOrEqual(t, len(body), 65536)
		if summary != "" {
			require.Contains(t, body, summary)
			require.Contains(t, body, "<td>1 statement</td>")
		} else {
			require.Equal(t, reportComment(t, r)+"\n<!-- generated by ariga/atlas-action for app -->", body)
		}
	}
}

func TestRenderLintComment_Open(t *testing.T) {
	// Files are open while their objects fit in 15 rows, counted across files in lint order.
	s := renderLint(t, lintReport(lintFile("1.sql", 10), lintFile("2.sql", 10), lintFile("3.sql", 5), lintFile("4.sql", 1)))
	for name, open := range map[string]bool{"1.sql": true, "2.sql": false, "3.sql": true, "4.sql": false} {
		d := "<details>"
		if open {
			d = "<details open>"
		}
		require.Contains(t, s, d+"<summary><strong>Changes in</strong> <code>"+name+"</code>")
	}
}

func TestRenderLintComment_SchemaOnly(t *testing.T) {
	// Statements that change no object count in their file, but have no row.
	f := lintFile("1.sql", 1)
	f.Stmts = append(f.Stmts, &migrate.Stmt{Text: "INSERT INTO \"t\" VALUES (1);"})
	f.Changes.Other, f.Changes.Stmts = []int{1}, 2
	s := renderLint(t, lintReport(f, dataFile("2.sql")))
	require.Contains(t, s, "<code>1.sql</code> · 1 object: 1 added · 2 statements</summary>")
	require.NotContains(t, s, "other statements")
	require.NotContains(t, s, "INSERT INTO")
	// Files without schema changes have no section, and with only them, the comment is as before.
	require.NotContains(t, s, "<code>2.sql</code>")
	r := lintReport(dataFile("1.sql"))
	s, err := renderLintComment(nil, &LintComment{Report: r}, githubCommentLimit)
	require.NoError(t, err)
	require.Equal(t, reportComment(t, r), s)
}

func TestRenderLintComment_Batch(t *testing.T) {
	// The objects of a file that runs as one batch have no statements, and no statements column.
	f := lintFile("1.sql", 2)
	for _, o := range f.Changes.Objects {
		o.Stmts = nil
	}
	f.Changes.Other = []int{0, 1}
	s := renderLint(t, lintReport(f))
	require.Contains(t, s, "<code>1.sql</code> · 2 objects: 2 added · 2 statements</summary><p></p>\n<table>\n<tr><th>Object</th><th>Diff</th></tr>")
	require.NotContains(t, s, "<th>Statements</th>")
	require.NotContains(t, s, "CREATE TABLE \"1_t0\" (\n  \"id\"")
}

func TestRenderLintComment_Limit(t *testing.T) {
	var (
		r      = lintReport(lintFile("1.sql", 20))
		before = reportComment(t, r)
		size   = func(sql bool) int {
			s, err := RenderTemplate("lint-changes.tmpl", &LintComment{Report: r, SummarySQL: sql}, nil)
			require.NoError(t, err)
			return len(before) + len(s)
		}
		full, counts = size(true), size(false)
	)
	require.Greater(t, full, counts)
	require.Greater(t, counts, len(before))
	// With the statements of each object, if they fit.
	c := &LintComment{Report: r}
	s, err := renderLintComment(nil, c, full)
	require.NoError(t, err)
	require.True(t, c.SummarySQL)
	require.Len(t, s, full)
	require.Contains(t, s, "<td><details><summary>1 statement</summary>")
	// With their counts only, if they don't.
	s, err = renderLintComment(nil, c, full-1)
	require.NoError(t, err)
	require.False(t, c.SummarySQL)
	require.Len(t, s, counts)
	require.Contains(t, s, "<td>1 statement</td>")
	// As before the summary, if even that doesn't fit.
	s, err = renderLintComment(nil, c, counts-1)
	require.NoError(t, err)
	require.Equal(t, before, s)
}

func TestRenderLintComment_NoSummary(t *testing.T) {
	// Without a change summary, as from CLIs that don't report it, the comment is the same
	// as before it, byte for byte. Other SCMs pass the report, and get the same comment.
	f := lintFile("1.sql", 2)
	f.Stmts, f.Changes = nil, nil
	// A summary that fails to render is left out too.
	broken := lintFile("2.sql", 2)
	broken.Changes.Objects[1] = nil
	for _, r := range []*atlasexec.SummaryReport{lintReport(f), lintReport(broken), lintReport(), {}} {
		s, err := renderLintComment(nil, &LintComment{Report: r, Colors: true}, githubCommentLimit)
		require.NoError(t, err)
		require.Equal(t, reportComment(t, r), s)
		require.True(t, strings.HasSuffix(s, "</table>"))
	}
}

func TestRenderLintComment_Delimiter(t *testing.T) {
	f := lintFile("1.sql", 2)
	f.Text = "-- atlas:delimiter \\nGO\n\n" + strings.ReplaceAll(f.Text, ");\n", ");\nGO\n")
	s := renderLint(t, lintReport(f))
	require.Contains(t, s, "```sql\n"+f.Stmts[1].Text+"\nGO\n```")
}

// lintFile returns a linted file that creates n tables, with a change summary.
func lintFile(name string, n int) *atlasexec.FileReport {
	f := &atlasexec.FileReport{Name: name, Changes: &atlasexec.ChangeSummary{Stmts: n}}
	var text strings.Builder
	for i := range n {
		table := fmt.Sprintf("%s_t%d", strings.TrimSuffix(name, ".sql"), i)
		stmt := fmt.Sprintf("CREATE TABLE %q (\n  \"id\" integer NOT NULL\n);", table)
		f.Stmts = append(f.Stmts, &migrate.Stmt{Pos: text.Len(), Text: stmt})
		fmt.Fprintln(&text, stmt)
		f.Changes.Objects = append(f.Changes.Objects, &atlasexec.ObjectChange{
			Type:   "table",
			Op:     "add",
			Object: fmt.Sprintf("table %q", table),
			Diff:   "+" + strings.ReplaceAll(stmt, "\n", "\n+"),
			Stmts:  []int{i},
		})
	}
	f.Text = text.String()
	return f
}

// dataFile returns a linted file without schema changes.
func dataFile(name string) *atlasexec.FileReport {
	stmt := "INSERT INTO \"t\" VALUES (1);"
	return &atlasexec.FileReport{
		Name:    name,
		Text:    stmt + "\n",
		Stmts:   []*migrate.Stmt{{Text: stmt}},
		Changes: &atlasexec.ChangeSummary{Other: []int{0}, Stmts: 1},
	}
}

// lintReport returns the lint report of the given files.
func lintReport(files ...*atlasexec.FileReport) *atlasexec.SummaryReport {
	r := &atlasexec.SummaryReport{Files: files}
	r.Env.Dir = "migrations"
	return r
}

// renderLint renders the lint comment with the change summary of its files.
func renderLint(t *testing.T, r *atlasexec.SummaryReport) string {
	t.Helper()
	s, err := renderLintComment(nil, &LintComment{Report: r}, githubCommentLimit)
	require.NoError(t, err)
	require.Contains(t, s, "<strong>Changes in</strong>")
	return s
}

// reportComment renders the lint comment of the report, without a change summary,
// as other SCMs do.
func reportComment(t *testing.T, r *atlasexec.SummaryReport) string {
	t.Helper()
	s, err := RenderTemplate("migrate-lint.tmpl", r, nil)
	require.NoError(t, err)
	return s
}
