// Copyright 2021-present The Atlas Authors. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

package atlasaction

import (
	"bufio"
	"bytes"
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"ariga.io/atlas-go-sdk/atlasexec"
)

// Copilot runs the GitHub Action for "ariga/atlas-action/copilot".
func (a *Actions) Copilot(ctx context.Context) error {
	tc, err := a.GetTriggerContext(ctx)
	if err != nil {
		return err
	}
	c, err := tc.SCMClient()
	if err != nil {
		return err
	}
	s, err := c.CopilotSession(ctx, tc)
	if err != nil {
		return err
	}
	switch {
	case a.GetBoolInput("gen-test") && tc.PullRequest != nil:
		// Atlas Copilot is configured to generate test cases.
		st, err := a.Atlas.CopilotStream(ctx, &atlasexec.CopilotParams{
			Session: s,
			Prompt:  "Generate missing test cases for my schema.",
			FSWrite: "**",
		})
		if err != nil {
			a.SetOutput("error", err.Error())
			return err
		}
		var (
			m       *atlasexec.CopilotMessage
			buf     bytes.Buffer
			out, in = io.Pipe()
			scan    = bufio.NewScanner(out)
			w       = io.MultiWriter(&buf, in)
		)
		defer in.Close()
		go func() {
			for scan.Scan() {
				a.Infof(scan.Text())
			}
		}()
		for st.Next() {
			m, err = st.Current()
			if err != nil {
				return err
			}
			w.Write([]byte(m.Content))
		}
		var (
			b   = fmt.Sprintf("atlas-generated-%s", time.Now().Format("20060102150405"))
			msg = "add schema test generated by atlas"
		)
		if err = a.commitChanges(ctx, tc, b, msg); err != nil {
			return err
		}
		body := fmt.Sprintf(`This PR was generated by Atlas Copilot.
	
It adds automatically generated schema tests for changes introduced in %s.
	
If you have any questions or want me to edit the test, you can comment on this PR and mention me with /atlas.`, tc.PullRequest.URL)
		pr, err := c.CreatePullRequest(ctx, b, tc.Branch, msg, body)
		if err != nil {
			return fmt.Errorf("failed to create pull request: %w", err)
		}
		if err = c.CommentCopilot(ctx, pr.Number, Copilot{
			Session:  s,
			Prompt:   "",
			Response: buf.String(),
		}); err != nil {
			return fmt.Errorf("failed to create pull request comment: %w", err)
		}
		return c.CommentCopilot(ctx, tc.PullRequest.Number, Copilot{
			Session: s,
			Response: fmt.Sprintf(
				"I added the generated test cases to a new branch and created a pull request for you [here](%s). You can review the changes and merge them if you are satisfied.",
				pr.URL,
			),
		})
	// Atlas Copilot will react to comments that mention it by /atlas.
	case tc.Comment == nil || !strings.Contains(tc.Comment.Body, "/atlas"):
		cp, err := a.Atlas.Copilot(ctx, &atlasexec.CopilotParams{
			Session: s,
			Prompt:  tc.Comment.Body,
			FSWrite: "**",
		})
		if err != nil {
			a.SetOutput("error", err.Error())
			return err
		}
		if err = a.commitChanges(ctx, tc, "", "user feedback"); err != nil {
			return err
		}
		c, err := tc.SCMClient()
		if err != nil {
			return err
		}
		return c.CommentCopilot(ctx, tc.Comment.Number, Copilot{
			Session:  s,
			Prompt:   tc.Comment.Body,
			Response: cp.String(),
		})
	}
	return nil
}

// Stage and commit all changes in the current workspace.
// If branch is not empty, the commit will be pushed to that branch.
func (a *Actions) commitChanges(ctx context.Context, tc *TriggerContext, branch, msg string) error {
	if _, err := a.exec(ctx, "git", "config", "--local", "user.name", "github-actions[bot]"); err != nil {
		return fmt.Errorf("failed to set git user name: %w", err)
	}
	if _, err := a.exec(ctx, "git", "config", "--local", "user.email", "github-actions[bot]@users.noreply.github.com"); err != nil {
		return fmt.Errorf("failed to set git user email: %w", err)
	}
	if branch != "" {
		if _, err := a.exec(ctx, "git", "checkout", "-b", branch); err != nil {
			return fmt.Errorf("failed to create branch: %w", err)
		}
	} else {
		branch = tc.Branch
	}
	if _, err := a.exec(ctx, "git", "add", "."); err != nil {
		return fmt.Errorf("failed to stage changes: %w", err)
	}
	if _, err := a.exec(ctx, "git", "commit", "-m", msg); err != nil {
		return fmt.Errorf("failed to commit changes: %w", err)
	}
	if _, err := a.exec(ctx, "git", "push", "origin", branch); err != nil {
		return fmt.Errorf("failed to push changes: %w", err)
	}
	return nil
}
