name: "Schema Push"
description: "Push a schema version with an optional tag to Atlas"
branding:
  icon: database
author: "Ariga"
inputs:
  working-directory:
    description: Atlas working directory, default is project root
    required: false
  config:
    description: |
      The path to the Atlas configuration file. By default, Atlas will look for a file
      named `atlas.hcl` in the current directory. For example, `file://config/atlas.hcl`.
      Learn more about [Atlas configuration files](https://atlasgo.io/atlas-schema/projects).
    required: false
  env:
    description: The environment to use from the Atlas configuration file. For example, `dev`.
    required: false
  vars:
    description: |
      A JSON object containing variables to be used in the Atlas configuration file.
      For example, `{"var1": "value1", "var2": "value2"}`.
    required: false
  dev-url:
    description: |
      The URL of the dev-database to use for analysis. For example: `mysql://root:pass@localhost:3306/dev`.
      Read more about [dev-databases](https://atlasgo.io/concepts/dev-database).
    required: false
  schema-name:
    description: |
      The name (slug) of the schema repository in Atlas Registry.
      Read more in Atlas website: https://atlasgo.io/registry.
    required: false
  url:
    description: |
      Desired schema URL(s) to push. For example: `file://schema.lt.hcl`.
    required: false
  description:
    description: The description of the schema changes.
    required: false
  version:
    description: The version of the schema changes.
    required: false
  tag:
    description: |
      The tag to apply to the pushed schema. By default, the current git commit hash is used.
    required: false
  latest:
    description: |
      If true, push also to the "latest" tag.
    default: "true"
    required: false
outputs:
  link:
    description: Link to the schema version on Atlas.
  slug:
    description: The slug of the pushed schema version.
  url:
    description: The URL of the pushed schema version.
runs:
  using: node20
  main: index.js
