name: Bats Tests
on:
  push:
    paths:
      - 'scripts/**'
      - '.github/workflows/ci-bats.yaml'
  pull_request:
    paths:
      - 'scripts/**'
      - '.github/workflows/ci-bats.yaml'
jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: ariga/setup-atlas@d1698c9cc991e6d65a02ce8bb9cd69fba6223cff # v0
      - name: Setup Bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@5b1e60c2ee94cb1b44a616ea4b1f466f9d6e38ef # 4.0.0
      - name: Run bats tests
        shell: bash
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
          TERM: xterm
        run: bats scripts/*.bats
