name: Go Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:
jobs:
  schema-lint:
    runs-on: ubuntu-latest
    env:
      ATLAS_ACTION_LOCAL: 1
    steps:
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go install ./cmd/atlas-action
        env:
          CGO_ENABLED: 0
      - id: schema_lint_test
        uses: ./schema/lint
        with:
          working-directory: atlasaction/testdata/schema-lint
          config: file://atlas.hcl
          dev-url: sqlite://file?mode=memory
          url: sqlite://schemarule.db
          vars: '{"rulefile":"schema.rule.hcl"}'
        env:
          GITHUB_TOKEN: ${{ github.token }}
  schema-lint-success:
    runs-on: ubuntu-latest
    env:
      ATLAS_ACTION_LOCAL: 1
    steps:
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go install ./cmd/atlas-action
        env:
          CGO_ENABLED: 0
      - id: schema_lint_test
        uses: ./schema/lint
        with:
          working-directory: atlasaction/testdata/schema-lint
          config: file://atlas.hcl
          dev-url: sqlite://file?mode=memory
          url: sqlite://schemarule.db
          vars: '{"rulefile":"schema.rule.hcl"}'
        env:
          GITHUB_TOKEN: ${{ github.token }}
 
