name: Go Continuous Integration
on:
  push:
    branches-ignore:
      - master
jobs:
  migrate-auto-rebase:
    permissions:
      contents: write  # allow pushing changes to repo
    runs-on: ubuntu-latest
    env:
      ATLAS_ACTION_LOCAL: 1
    steps:
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_TOKEN }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go install ./cmd/atlas-action
        env:
          CGO_ENABLED: 0
      - uses: ./migrate/autorebase
        with:
          dir: file://migrations
          base-branch: test_use_merge_to
