name: Go Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:

#permissions:
#  contents: write
#  pull-requests: write

jobs:
  shim-e2e:
    runs-on: ubuntu-latest
    env:
      ATLAS_ACTION_LOCAL: 0 # Disable local mode
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - uses: ariga/setup-atlas@master
        with:
          cloud-token: ${{ secrets.ATLAS_TOKEN }}
      - name: "Run Migrate Lint"
        run: go run cmd/atlas-action/main.go --action migrate/lint
        env:
          INPUT_DIR: file://atlasaction/testdata/migrations
          INPUT_DEV-URL: sqlite://db?mode=memory
          INPUT_DIR-NAME: noam-test
          INPUT_AUTO-HASH: true
#          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}