name: release-action
on:
  push:
    tags: "v*"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
        target-os: linux
        target-architecture: amd64
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          path: build/
      - name: publish a release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{  github.ref_name }} build/*/*
